name: Build and Deploy WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Verify Emscripten
      run: emcc -v

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev

    - name: Build WASM (Debug)
      run: |
        make

    - name: Build WASM (Release)
      run: |
        make TYPE=release

    - name: Copy additional files
      run: |
        cp post.js build/debug/
        cp template.html build/debug/
        cp post.js build/release/
        cp template.html build/release/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

    - name: Start local server for testing
      run: |
        python -m http.server 8000 --directory build/debug &
        sleep 5
        curl http://localhost:8000/miner.html
