name: Build and Deploy WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Verify Emscripten
      run: emcc -v

    - name: Install Boost
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
        tar xzf boost_1_76_0.tar.gz
        cd boost_1_76_0
        ./bootstrap.sh
        ./b2 headers

    - name: Install libsodium
      run: |
        git clone https://github.com/jedisct1/libsodium.git
        cd libsodium
        git checkout stable
        ./autogen.sh
        emconfigure ./configure --prefix=$HOME/libsodium --disable-shared
        emmake make
        emmake make install

    - name: Debug - List directory structure
      run: |
        echo "Project structure:"
        find . -type d
        
    - name: Debug - List source files
      run: |
        echo "Source files:"
        find src -name '*.cpp'

    - name: Build WASM
      run: |
        mkdir -p build/debug
        source_files=$(find src src/crypto src/common src/contrib/epee/include -name '*.cpp' -or -name '*.c')
        emcc $source_files \
        -I src -I src/crypto -I src/common -I src/contrib/epee/include \
        -I boost_1_76_0 -I$HOME/libsodium/include \
        -L$HOME/libsodium/lib -lsodium \
        -s WASM=1 -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' \
        -s ERROR_ON_UNDEFINED_SYMBOLS=0 \
        --shell-file template.html --post-js post.js \
        -o build/debug/miner.html

    - name: Copy additional files
      run: |
        cp post.js build/debug/
        cp template.html build/debug/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/debug
