name: Build and Deploy WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Verify Emscripten
      run: emcc -v

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev

    - name: Build WASM
      run: |
        mkdir -p build/debug
        emcc src/*.cpp src/crypto/*.cpp src/common/*.cpp src/contrib/epee/include/*.cpp \
        -I src -I src/crypto -I src/common -I src/contrib/epee/include \
        -s WASM=1 -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' \
        --shell-file template.html --post-js post.js \
        -o build/debug/miner.html

    - name: Copy additional files
      run: |
        cp post.js build/debug/
        cp template.html build/debug/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/debug
